model:
  name: "facebook/mbart-large-50-many-to-many-mmt"
  local_path: "../training/outputs/mbart/translation/model"
  max_length: 128
  device: 'cuda'

data:
  path: "../../data/abx_sentences.csv"
  task:
    format: "ABX"
    src_lang_code: "sw_KE"
    tgt_lang_code: "en_XX"

inference:
  batch_size: 64

outputs:
  save_dir: "./outputs/mbart/translation/embeds"

wandb:
  project: "Tira-LM"
  run_name: "mbart-embedding-comparison"
