# equivalent to 'translation.yaml' but applies mapping on parenthetical substrings
# as specified in ../../doc/parentheticals.tsv
model:
  name: "facebook/mbart-large-50-many-to-many-mmt"
  max_length: 128

data:
  hf_uri: "tira-parsing/tira-parsing"
  columns:
    input_column: "orig_text"
    target_column: "translation"
  task:
    format: "mbart"
    src_lang_code: "sw_KE"
    tgt_lang_code: "en_XX"
    parenthetical_beahvior: "transform"
    parenthetical_map_file: "../../doc/parentheticals.tsv"

training:
  output_dir: './outputs/mbart/translation_parens'
  learning_rate: 2e-5
  batch_size: 16
  grad_acc: 2
  weight_decay: 0.01
  epochs: 20
  bf16: true
  save_total_limit: 2
  logging_steps: 50

wandb:
  project: "Tira-LM"
  run_name: "mbart-translation"
